# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  # Disable GUI
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  # Forward X
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # Open port 1337
  config.vm.network "forwarded_port", guest: 1337, host: 1337
end
