# Bottom config file
# See https://github.com/ClementTsang/bottom#config-files

[flags]
dot_marker = false
left_legend = true

[colors]
highlighted_border_color = "Yellow"
widget_title_color="Yellow"
avg_cpu_color = "White"

# Layout
[[row]]
  ratio=20
  [[row.child]]
  type="cpu"
[[row]]
  ratio=70
  [[row.child]]
    ratio=2
    type="proc"
    default=true
  [[row.child]]
    [[row.child.child]]
      ratio=2
      type="mem"
    [[row.child.child]]
      ratio=2
      type="net"
    [[row.child.child]]
      type="disk"
    [[row.child.child]]
      type="temp"

