#!/bin/bash

# Wrapper to run rofi with blurred background

/usr/bin/rofi -font 'Source Code Pro for Powerline 10' -opacity 85 $@ &
xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $(xdotool search --sync --onlyvisible -name 'rofi')
