#!/bin/bash

# Wrapper run spotify with blurred background

spotify $@ 
while ! xdotool search -class 'spotify'; do sleep 0.5; done
xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $(xdotool search -class 'spotify' | sort | tail -n1)

