#!/bin/bash

# Wrapper run spotify with blurred background

spotify $@ 
xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $(xdotool search --sync --onlyvisible 'spotify' | sort | tail -n1)

