# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<-SCRIPT
# INSTALL SOFTWARE
sudo apt update
sudo apt install -y vim-gtk3 docker.io npm fzf xclip patchelf hexedit cargo ghidra gdbserver ripgrep strace gdb imagemagick feh peass golang-go xxd
env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
curl -sOL https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom_0.9.6_amd64.deb --output-dir /tmp && sudo dpkg -i /tmp/bottom_0.9.6_amd64.deb
pip install pwntools z3 ortools

# CHANGE SHELL AND SETUP DOTFILES
sudo chsh vagrant -s /bin/bash
sudo localectl set-locale LANG=en_CA.UTF-8
# Fix X11 sharing timeout for gnome windows
echo 'eval `dbus-launch --sh-syntax`' >> ~/.profile
sudo usermod -a -G docker vagrant
ssh-keyscan github.com >> .ssh/known_hosts
git clone git@github.com:3ximus/dotfiles --depth 1 --recurse-submodules -j4 --shallow-submodules /home/vagrant/dotfiles
cd ~/dotfiles && ./install/config.sh --force --post --batch

# SET DARK THEMES
mkdir -p ~/.ghidra/.ghidra_11.0_DEV/ && echo "Theme=Class\:generic.theme.builtin.FlatDarkTheme" > ~/.ghidra/.ghidra_11.0_DEV/preferences
mkdir -p ~/.BurpSuite && echo '{"user_options":{"display":{"user_interface":{"look_and_feel":"Dark"}},"misc":{"hotkeys":[{"action":"open_embedded_browser","hotkey":"Ctrl+P"}]}}}' > ~/.BurpSuite/UserConfigCommunity.json

# OTHER SMALL TWEAKS TO SIMPLIFY LAUNCHING PROCESS
ln -s /vagrant ~/vagrant
sudo gunzip /usr/share/wordlists/rockyou.txt.gz
echo | sudo tee /etc/motd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.define "kali"
  config.vm.box_check_update = false

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 8192
    libvirt.memorybacking :access, :mode => "shared"
  end

  config.vm.synced_folder "./", "/vagrant", type: "virtiofs"

  # this prevents new ssh key from being generated for this box but shouldn't be needed anymore
  # there was a bug where the private key was missing a new line at the end of the file
  # config.ssh.insert_key = false

  # Forward X
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # Open ports
  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "shell", inline: $provision_script, privileged: false
end
