# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_personal = <<-SCRIPT
sudo apt install -y ghidra &

sudo localectl set-locale LANG=en_CA.UTF-8
echo 'eval `dbus-launch --sh-syntax`' >> ~/.profile # Fix X11 sharing timeout for gnome windows
ssh-keyscan github.com >> .ssh/known_hosts
git clone https://github.com/3ximus/dotfiles.git --depth 1 --recurse-submodules -j4 /home/vagrant/dotfiles
cd ~/dotfiles && ./install/config.sh --force --post --batch
SCRIPT

$provision_tweaks = <<-SCRIPT
# SET DARK THEMES
mkdir -p ~/.ghidra/.ghidra_11.0_DEV/ && echo "Theme=Class\:generic.theme.builtin.FlatDarkTheme" > ~/.ghidra/.ghidra_11.0_DEV/preferences
mkdir -p ~/.BurpSuite && echo '{"user_options":{"display":{"user_interface":{"look_and_feel":"Dark"}},"misc":{"hotkeys":[{"action":"open_embedded_browser","hotkey":"Ctrl+P"}]}}}' > ~/.BurpSuite/UserConfigCommunity.json

# OTHER SMALL TWEAKS TO SIMPLIFY LAUNCHING PROCESS
[[ -d /vagrant/desk ]] && ln -s /vagrant/desk ~/desk
[[ -d /vagrant/ctf ]] && ln -s /vagrant/ctf ~/ctf
[[ -d /vagrant/vpn ]] && ln -s /vagrant/ctf ~/vpn
sudo gunzip /usr/share/wordlists/rockyou.txt.gz
echo | sudo tee /etc/motd
echo -e "\nSome software is still being installed through apt and might not yet be available when started."
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "0rr0rs/kali"
  config.vm.define "kali"
  config.vm.box_check_update = true

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.cpus = 8
    libvirt.memory = 8192
    libvirt.memorybacking :access, :mode => "shared"

    libvirt.graphics_type  = "spice"
    libvirt.nic_model_type = "virtio"
    libvirt.sound_type     = "ich6"
    libvirt.video_type     = "qxl"

    libvirt.channel :type  => 'spicevmc', :target_name => 'com.redhat.spice.0',     :target_type => 'virtio'
    libvirt.channel :type  => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.random  :model => 'random'
  end

  config.vm.synced_folder "./", "/vagrant", type: "virtiofs"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.network "forwarded_port", guest: 4444, host: 4444
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provision "shell", inline: $provision_personal, privileged: false
  config.vm.provision "shell", inline: $provision_tweaks, privileged: false
end

