#! /bin/sh

if [[ $(hostname) == 'mercury' ]]; then
	bspc monitor -d I II III IV V VI
elif [[ $(hostname) == 'mars' ]]; then
	bspc monitor HDMI-0 -d I II III IV V
	bspc monitor DVI-I-0 -d VI VII VIII IX X
fi

bspc config border_width            0
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#665c54"
bspc config presel_feedback_color   "#7c6f64"

bspc condig pointer_modifier mod2 # use Alt key with mouse to move windows

# bspc rule -a urxvt desktop='^1' focus=on
bspc rule -a Firefox desktop='^2' focus=on
bspc rule -a Vivaldi-stable desktop='^2' focus=on
bspc rule -a whatsapp-nativefier-7bbd2c desktop='^5' focus=on

bspc config external_rules_command $HOME/.config/bspwm/external_rules

polybar bar &
