#! /bin/sh

# start hotkey daemon
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            0
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#665c54"
bspc config presel_feedback_color   "#7c6f64"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Screenkey manage=off

polybar bar &
