# -*- mode: ruby -*-
# vi: set ft=ruby :

$provision_script = <<-SCRIPT
sudo apt update && sudo apt install -y git make gawk
ssh-keyscan github.com >> .ssh/known_hosts
git clone git@github.com:3ximus/dotfiles --recurse-submodules -j8 ~/dotfiles
cd ~/dotfiles && ./install/config.sh --force --post --batch
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.define "debian-test"

  config.vm.provider 'libvirt' do |libvirt|
    libvirt.memorybacking :access, :mode => "shared"
  end

  config.ssh.insert_key = false

  config.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "squash"
  config.ssh.forward_agent = true

  config.vm.provision "shell", inline: $provision_script, privileged: false
end
